version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/home/irfan/Documents/Builds/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: max
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    # - MONGO_INITDB_ROOT_USERNAME=max
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - '8000:8000'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
# Important Notes:
########################3
# RUN
# Run docker compose with below command in detache mode
# docker-compose up -d

# Stop
# Stop docker compose with below command with -v to remove the volumes
# docker-compose down -v

#Note:
# 80 is default port of server so below
# localhost/goals is relaced with localhost:8000/goals

# For some reason volumes are not working......
